[project]
name = "drawlab"
version = "0.1.0"
description = "A modular diagram generation system for infrastructure and architecture diagrams"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["diagrams>=0.24.4"]
